package org.uengine.visualmashup.dao;

import org.uengine.visualmashup.model.Entity;
import org.uengine.visualmashup.model.WhereClause;

import java.util.List;

/**
 * DAO SQL Mapper 공통 기능 정의 인터페이스
 *
 * @author 이승백
 */
public interface DAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    int countByWhereClause(WhereClause whereClause);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    int insert(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    List<? extends Entity> selectByWhereClause(WhereClause whereClause);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    Entity selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_gadgets
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Entity record);
}